### ISSUE TITLE
[Bug]: Warning: Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by yilmazcabuk** [movie-web/movie-web#296]
### What happened?

The media should open without any error or warning messages in the console but when opening the media for the second time, the following warning message appears in the console:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at BackdropAction (http://localhost:5173/src/video/components/actions/BackdropAction.tsx?t=1683985368222:24:22)
    at VideoPlayerError (http://localhost:5173/src/video/components/parts/VideoPlayerError.tsx:26:22)
    at div
    at div
    at VideoErrorBoundary (http://localhost:5173/src/video/components/parts/VideoErrorBoundary.tsx:10:5)
    at VideoPlayerBaseWithState (http://localhost:5173/src/video/components/VideoPlayerBase.tsx:28:15)
    at VideoPlayerContextProvider (http://localhost:5173/src/video/state/hooks.tsx:22:23)
    at VideoPlayerBase
    at VideoPlayer (http://localhost:5173/src/video/components/VideoPlayer.tsx?t=1683985368222:110:27)
    at div
    at MediaViewPlayer (http://localhost:5173/src/views/media/MediaView.tsx?t=1683985368222:182:18)
    at MediaView (http://localhost:5173/src/views/media/MediaView.tsx?t=1683985368222:252:18)
```

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Steps to reproduce?

1. Start the application.
2. Search for any media.
3. Open the media.
4. Go back using the back button.
5. Open the media again.

### Other relevant information

This warning message indicates a memory leak in the application. To fix the issue, all subscriptions and asynchronous tasks in a useEffect cleanup function should be cancelled.

**Comment by mrjvs** [comment]
As this only happens one time on mount/unmount (so not a leak) and its a no-op. I dont think we have to spend tons of time to find the bug to fix it.

If you really want it gone, you can make a pr to fix it.
