### ISSUE TITLE
[Bug]: Cannot deploy backend on server

### ISSUE THREAD

**Issue by KyleJKC** [movie-web/movie-web#651]
### What happened?

I was trying to deploy the backend on my Ubuntu 22.04 server.

After I ran
```
docker run \
    -p 80:80 \
    -e POSTGRES__CONNECTION=postgresql://localhost:5432 \
    -e CRYPTO__SESSION_SECRET=rmyQQJZhCiL27y57yHU0aNQThiTBCxPu \
    -e META__NAME=unofficial-movie-web \
    [ghcr.io/movie-web/backend:latest](http://ghcr.io/movie-web/backend:latest)
```

I got:
```
> backend@1.2.1 start /app
> node dist/main.js

/app/node_modules/.pnpm/neat-config@2.0.0/node_modules/neat-config/lib/schemas/zod.js:15
        throw result.error; // TODO better errors
        ^

ZodError: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [
      "postgres"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [
      "crypto"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [
      "meta"
    ],
    "message": "Required"
  }
]
    at get error [as error] (/app/node_modules/.pnpm/zod@3.22.4/node_modules/zod/lib/types.js:43:31)
    at validateObjectWithZodSchema (/app/node_modules/.pnpm/neat-config@2.0.0/node_modules/neat-config/lib/schemas/zod.js:15:22)
    at validateObjectWithSchema (/app/node_modules/.pnpm/neat-config@2.0.0/node_modules/neat-config/lib/builder/schema.js:33:54)
    at Object.load (/app/node_modules/.pnpm/neat-config@2.0.0/node_modules/neat-config/lib/builder/builder.js:96:60)
    at Object.<anonymous> (/app/dist/config/index.js:25:6)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'object',
      received: 'undefined',
      path: [ 'postgres' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'object',
      received: 'undefined',
      path: [ 'crypto' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'object',
      received: 'undefined',
      path: [ 'meta' ],
      message: 'Required'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'object',
      received: 'undefined',
      path: [ 'postgres' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'object',
      received: 'undefined',
      path: [ 'crypto' ],
      message: 'Required'
    },
    {
      code: 'invalid_type',
      expected: 'object',
      received: 'undefined',
      path: [ 'meta' ],
      message: 'Required'
    }
  ]
}

Node.js v20.10.0
 ELIFECYCLE  Command failed with exit code 1.
```

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

By running
```
docker run \
    -p 80:80 \
    -e POSTGRES__CONNECTION=postgresql://localhost:5432 \
    -e CRYPTO__SESSION_SECRET=rmyQQJZhCiL27y57yHU0aNQThiTBCxPu \
    -e META__NAME=unofficial-movie-web \
    [ghcr.io/movie-web/backend:latest](http://ghcr.io/movie-web/backend:latest)
```

### Other relevant information

I think that was because I had to deploy an instance of PostgreSQL.

However, after I created the database, it still gave me the same error.

Am I missing any step here?

**Comment by mrjvs** [comment]
Env keys needs to be prefixed with `MWB_`. See the docs: https://docs.movie-web.app/backend/configuration#method-2-env

Also get a new session key when you do, this one is now public and thus unsafe.

**Comment by KyleJKC** [comment]
> Env keys needs to be prefixed with `MWB_`. See the docs: https://docs.movie-web.app/backend/configuration#method-2-env
> 
> Also get a new session key when you do, this one is now public and thus unsafe.

Thank you so much for your reply.

I changed my command accordingly, but new problem appeared:
<img width="994" alt="Screenshot 2023-12-29 at 6 24 39 PM" src="https://github.com/movie-web/movie-web/assets/44722594/952b6951-468b-4c5e-a801-4e77d3a0bec2">
